PracticaCore2Iniciales/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PracticaCore2Iniciales.Models;
using PracticaCore2Iniciales.Repositories;
using PracticaCore2Iniciales.Extensions;
using Microsoft.AspNetCore.Http;

namespace PracticaCore2Iniciales.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        //Mostrar todos los libros
        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        //Mostrar los generos
        public IActionResult Index()
        {

            List<Libro> libros = this.repo.GetLibros();


            return View(libros);
        }


        public IActionResult DetallesLibro(int idlibro)
        {
            Libro libro = this.repo.DetallesLibro(idlibro);
            return View(libro);
        }


        public IActionResult LibrosGenero(int idgenero)
        {
            List<Libro> libros = this.repo.LibrosGenero(idgenero);
            return View(libros);
        }

        public IActionResult CarritoLibros(int? idlibro)
        {
            if (idlibro != null)
            {
                List<int> lstLibrosId;
                if (HttpContext.Session.GetString("Idlibro") == null)
                {
                   
                    lstLibrosId = new List<int>();
                }
                else
                {
                    
                    lstLibrosId =
             HttpContext.Session.GetObject<List<int>>("Idlibro");
                }
                
                lstLibrosId.Add(idlibro.Value);
           
                HttpContext.Session.SetObject("Idlibro", lstLibrosId);
            }
            return View(this.repo.GetLibros());

        }


    }
    }

PracticaCore2Iniciales/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PracticaCore2Iniciales.Filters;
using PracticaCore2Iniciales.Models;
using PracticaCore2Iniciales.Repositories;
using System.Security.Claims;

namespace PracticaCore2Iniciales.Controllers
{
    public class UsuariosController : Controller
    {
        private RepositoryLibros repo;
        public UsuariosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }


        [AthorizeUser]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Perfil(int idusuario)
        {
            idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Usuario usuario = this.repo.GetUsuario(idusuario);

            return View(usuario);
        }

        [AthorizeUser]
        public IActionResult FinalizarCompra(int idpedido, int idfactura, long fecha, int idusuario, int cantidad)
        {
            int results = this.repo.FinalizarCompra( idpedido, idfactura, fecha, idusuario, cantidad);
          ViewData["MENSAJECONFIRMACION"] = "Compra realizada";
            

            return View();
        }


    }
}

PracticaCore2Iniciales/ViewComponents/MenuLibrosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PracticaCore2Iniciales.Repositories;
using PracticaCore2Iniciales.Models;

namespace PracticaCore2Iniciales.ViewComponents
{
    public class MenuLibrosViewComponent : ViewComponent
    {
        private RepositoryLibros repo;
        public MenuLibrosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = this.repo.GetGeneros();
            return View(generos);
        }
    }
}

PracticaCore2Iniciales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaCore2Iniciales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Expand at sm</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Libros" asp-action="Index">Libros</a>
                    </li>

                    <li class="nav-item dropdown">
                        @await Component.InvokeAsync("MenuLibros")

                    </li>
                    <li class="nav-item dropdown">
                     <a class="nav-link" asp-controller="Libros" asp-action="CarritoLibros">Carrito</a>

                    </li>
                        <partial name="_UsuarioPartial" />
                </ul>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PracticaCore2Iniciales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaCore2Iniciales/Views/Shared/_UsuarioPartial.cshtml
@if (Context.Session.GetString("Idlibro") != null)
{

    <li>
       
        <span style="color:red">Libros: @Context.Session.GetString("Idlibro").Count()</span>
    </li>
}
@if (Context.User.Identity.IsAuthenticated == false)
{

<li class="nav-item">
    <a class="nav-link mx-2" asp-controller="Usuarios" asp-action="Index">
        <i class="fas fa-heart pe-2"></i>Login
    </a>
</li>
}


else
{
<li>
    Hola, @Context.User.Identity.Name
    <img style="width:35px; height:35px" src="~/Images/@Context.User.FindFirst("Foto")" />
</li>
<li class="nav-item">
    <a class="nav-link mx-2" asp-controller="Usuarios" asp-action="Perfil">
        <i class="fas fa-heart pe-2"></i>Perfil
    </a>
</li>
<li class="nav-item">
    <a id="LogoLogout" class="nav-link mx-2" asp-controller="Manage" asp-action="LogOut">
        LogOut
    </a>
</li>
}